# Generated by Django 3.2.4 on 2021-06-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='img', verbose_name='Your  Photo ')),
                ('NameAndSurname', models.CharField(max_length=999, verbose_name='Amir Mohamadi ')),
                ('Job', models.CharField(max_length=999, verbose_name='Web Developer ')),
                ('Instagram', models.CharField(max_length=999, verbose_name='Instagram Link')),
                ('Twitter', models.CharField(max_length=999, verbose_name='Twitter Link ')),
                ('Facebook', models.CharField(max_length=999, verbose_name='Facebook Link ')),
                ('AboutMe', models.TextField(verbose_name='About Me ')),
            ],
        ),
    ]
