# Generated by Django 3.2.4 on 2021-06-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='Telegram',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='Telegram Link '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='Instagram',
            field=models.CharField(max_length=999, verbose_name='Instagram Link '),
        ),
    ]
