# Generated by Django 3.2.4 on 2021-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0002_auto_20210616_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='Facebook',
            field=models.CharField(max_length=999, verbose_name='Facebook Id '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='Instagram',
            field=models.CharField(max_length=999, verbose_name='Instagram Id '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='Telegram',
            field=models.CharField(blank=True, max_length=999, null=True, verbose_name='Telegram Id '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='Twitter',
            field=models.CharField(max_length=999, verbose_name='Twitter Id '),
        ),
    ]
