# Generated by Django 3.2.4 on 2021-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site_settings', '0004_sitesettings_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='Job',
            field=models.CharField(max_length=999, verbose_name='Job : Web Developer '),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='NameAndSurname',
            field=models.CharField(max_length=999, verbose_name='Name And Surname '),
        ),
    ]
